@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:Delete success;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Person was in displayed list])
else ([else])
    :Display all Persons;
endif
stop
@enduml
