@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class Id {
    - {static} nextId : int
    - Id()
    -Id(int)
    +generateNextId() : Id
    +generateId() : Id
    +generateTempId(int) : Id
}
@enduml
