@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "NetConnect Storage" #F4F6F6{
Class "<<interface>>\nNetConnectStorage" as NetConnectStorage
Class JsonNetConnectStorage
Class JsonSerializableNetConnect
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "State Storage" #F4F6F6{
Class "<<interface>>\nStateStorage" as StateStorage
Class TextNetConnectStorage

}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" NetConnectStorage
StorageManager -up-> "1" StateStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> NetConnectStorage
Storage -right-|> StateStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonNetConnectStorage .up.|> NetConnectStorage
TextNetConnectStorage .up.|> StateStorage
JsonNetConnectStorage ..> JsonSerializableNetConnect
JsonSerializableNetConnect --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
