@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12


title Activity: Unrelate command
start
:User executes unrelate command;

if () then ([else])
    :Show error message;
else ([two numeric IDs provided])
    if () then ([else])
        :Show error message;
    else ([Both IDs exist])
        :Unrelate both profiles to each other;
        :Display both profiles that have been unrelated;
    endif
endif
stop
@enduml
