@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":NetConnectParser" as NetConnectParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "id:Id" as Id LOGIC_COLOR
participant "DeleteCommand" as DeleteFactory << class >> LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
end box

[-> LogicManager : execute("delete i/1")
activate LogicManager

LogicManager -> NetConnectParser : parseCommand("delete i/1")
activate NetConnectParser

create DeleteCommandParser
NetConnectParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> NetConnectParser
deactivate DeleteCommandParser

NetConnectParser -> DeleteCommandParser : parse("i/1")
activate DeleteCommandParser

create Id
DeleteCommandParser -> Id
activate Id

Id --> DeleteCommandParser
deactivate Id

DeleteCommandParser -> DeleteFactory : byId(id)
activate DeleteFactory

create DeleteCommand
DeleteFactory -> DeleteCommand :
activate DeleteCommand

DeleteCommand --> DeleteFactory :
deactivate DeleteCommand

DeleteFactory --> DeleteCommandParser : d
deactivate DeleteFactory

DeleteCommandParser --> NetConnectParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> NetConnectParser
destroy DeleteCommandParser

NetConnectParser --> LogicManager : d
deactivate NetConnectParser

ref over LogicManager : execute delete command

[<--LogicManager
deactivate LogicManager
@enduml
